-   id: {entry}
    name: {name}
    entry: {entry}
    language: {language}
    '{match_key}': {match_val}
    args: {args}
    require_serial: {require_serial}
    additional_dependencies: {additional_dependencies}
